language: php
php:
- 5.6
- 7.1
sudo: false
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - resources/vendor
  - "$HOME/.composer/cache"
before_install:
- openssl aes-256-cbc -K $encrypted_73c066875ca0_key -iv $encrypted_73c066875ca0_iv
  -in .travis/github_deploy_key.enc -out .travis/github_deploy_key -d
- mv .travis/github_deploy_key ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
install:
- nvm install 6
- npm install -g yarn
- yarn install
- npm rebuild node-sass
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- ls -la resources/style.css resources/index.php resources/vendor/autoload.php
- composer test
- bash bin/create-release-branch.sh
after_success:
- pwd
- ls -al
before_deploy:
- git clone -b release --quiet git@github.com:inc2734/mimizuku.git release
- cp package.json gulpfile.js yarn.lock release
- cd release
- yarn install
- yarn run gulp zip
- ls -la mimizuku.zip
- export RELEASE_FILE=$(ls mimizuku.zip)
deploy:
  provider: releases
  api_key:
    secure: YUflTF70/QimcqH0VuQui/TMKzbSJM12VDE4CC27s0KMvjznEANLpzthtvG/eaTjgVHRA1ccoOLobLDF7OQEdcr65Qqps8d3N188viQf51xnb1prV7q3SnyaRhHwaTE/Fb/e0LI+GgwD62GAQ3V8x7prVmRdQeL8fRslARmnmJICIzUMpWP9z+hFHo6l/diKTiyI/9bzSyYgz6EFoMpKCo/nG7E3wfpkO+WihXA9rM4AFdP7xacB0W8nYTH9LL4FVjo4chppPyxRaO+X/R1o5xQ5f11jUPqq5qryRINm94Y3/H1TyI37IzuwiPr3XR1xZy+B/ATH9X7tb+bvYRKkmva2gfLEHC3AbGwQm/Ls01ZtzT+ihqoJUNuWv9add0RttjFzLcZrCAmLIdkcTmAwMwf2XOBST4jryyocYh+mgZP4on2w71g8klrMzRsRrp+djmeY7hs3usmmEehQFw3mibbl4dzMK+pJa/fkztK+l/Mi5NMJnudnFkKIRjITfGYfd+fBw0c0J2pIVejvGBb51WLPokaI64lqszKrv5DNFNzO5bC1FkjN9fp6bX/OVRTQD41ZV1WzDeBXwo3K6SEaeTCsdd0GgkUinAj1mhFbPQqZpYdZyTB/RdEjrpOG5Lx/x5jFLwMk8WR6eM8Y6K4V9vu+8CXtWfiAAo871mbogCE=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: inc2734/mimizuku
